- name: deploy redisproxy
  hosts: all
  user: op_DBA01
  gather_facts: false
  tasks:
  - name: mkdir
    file: path=/data/install state=directory mode="0755"

  - name: tar xvf redisproxy_gray.tar.gz
    unarchive: src=redisproxy_gray.tar.gz dest=/data/install/

  - name:
    shell: su - web -c  "cd /data/install/redisproxy; sh start_{{idc}}.sh  {{proxyargs}}"
